Summary:	GNU Find Utilities (find, xargs)
Summary(de):	GNU-Suchprogramme (find, xargs)
Summary(fr):	Utilitaires de recherche de GNU (find, xargs)
Summary(pl):	GNU narzêdzia do odnajdywania plików (find, xargs)
Summary(tr):	GNU dosya arama araçlarý
Name:		findutils
Version:	4.1.7
Release:	2
Epoch:		1
License:	GPL
Group:		Applications/File
Group(de):	Applikationen/Datei
Group(pl):	Aplikacje/Pliki
Source0:	ftp://alpha.gnu.org/gnu/%{name}-%{version}.tar.gz
Patch0:		%{name}-info.patch
Patch1:		%{name}-pl_manpages.patch
Patch2:		%{name}-mktemp.patch
Patch3:		%{name}-getshort.patch
Patch4:		%{name}-DESTDIR.patch
Patch5:		%{name}-am-workaround.patch
BuildRequires:	texinfo
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
The findutils package contains programs which will help you locate
files on your system. The find utility searches through a hierarchy of
directories looking for files which match a certain set of criteria
(such as a filename pattern). The locate utility searches a database
(create by updatedb) to quickly find a file matching a given pattern.
The xargs utility builds and executes command lines from standard
input arguments (usually lists of file names generated by the find
command).

%description -l de
Das findutils-Paket enthält Programme, die dabei helfen, Dateien auf
Ihrem System zu finden. Das Find-Utility durchsucht die
Verzeichnishierarchie nach Dateien, die zu bestimmten Kriterien (z.B.
Dateiname) passen. Das locate-Utility durchsucht eine Datenbank
(erzeugt durch updatedb), um die Dateien schneller finden zu können.
xargs konstruiert Kommandozeilen von der Standardeingabe (z.B.
Dateilisten, die von find erzeugt werden), und führt sie aus.

%description -l fr
Ce package contient des programmes pour vous aider à localiser des
fichiers sur votre système. Le programme find peut rechercher à
travers une hiérarchie de répertoires des fichiers conformes à
certains critères (comme un type de nom).

%description -l pl
W pakiecie znajduj± siê narzêdzia pozwalaj±ce na poszukiwanie
okre¶lonych plików. Program find s³u¿y do poszukiwania w drzewie
katalogów plików o okre¶lonych parametrach, jak nazwa, uprawnienia,
typ czy data ostatniej modyfikacji.

%description -l tr
Bu pakette yer alan yazýlýmlar sisteminizde yer alan dosyalarý
bulabilmeniz için hazýrlanmýþlardýr. find programý ile belirli
özellikleri olan bir yazýlýmý bir dizin hiyerarþisi altýnda
arayabilirsiniz.

%prep
%setup  -q
%patch0 -p1 
%patch1 -p1
%patch2 -p1 
%patch3 -p1
%patch4 -p1
%patch5 -p1

%build
touch lib/{stat,lstat}.c
%configure 

%{__make}

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT%{_mandir}/pl/man1

%{__make} install \
	DESTDIR=$RPM_BUILD_ROOT
	
install pl/*.1  $RPM_BUILD_ROOT%{_mandir}/pl/man1

gzip -9nf NEWS README TODO ChangeLog
	
%find_lang %{name}

%post
%fix_info_dir

%postun
%fix_info_dir

%clean
rm -rf $RPM_BUILD_ROOT

%files -f %{name}.lang
%defattr(644,root,root,755)
%doc {NEWS,README,TODO,ChangeLog}.gz
%attr(755,root,root) %{_bindir}/find
%attr(755,root,root) %{_bindir}/xargs

%{_mandir}/man1/find.1*
%{_mandir}/man1/xargs.1*
%lang(pl) %{_mandir}/pl/man1/*
%{_infodir}/find.info*
